import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import ItemModal from '../components/itemModal'
import { shoppingItem } from '@prisma/client'
import prisma from "../prisma/prisma"
import ToggleItem from '../components/toggleItem'

//Interface for the props
interface PageProps {
  items: shoppingItem[]
}

const Home: NextPage<PageProps> = ({ items }) => {
  const [showModal, setShowModal] = useState(false)

  return (
    <>
      <Head>
        <title>Shopping list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {showModal && <ItemModal setShowModal = {setShowModal} items = { items } />}

      <main className='mx-auto my-12 max-w-3xl'>
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">Shopping List</h2>
          <button type='button' onClick={ () => setShowModal(true) } className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded drop-shadow-md"> Add Item </button>
        </div>       
        <ul className="mt-4">
          {items.map((item) => {
            return (
              <ToggleItem key = {item.id} {...item}/>
            )
          })}
        </ul>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const items = await prisma.shoppingItem.findMany()
  return {
    props: {
      items,
      checked: false
    },
  }

}

export default Home
