import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import ItemModal from '../components/itemModal'
import { shoppingItem } from '@prisma/client'
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

interface PageProps {
  items: shoppingItem[];
}

const Home: NextPage<PageProps> = ({ items }) => {
  const [showModal, setShowModal] = useState(false);

  return (
    <>
      <Head>
        <title>Shopping list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {showModal && <ItemModal setShowModal = {setShowModal} items = { items } />}


      <main className='mx-auto my-12 max-w-3xl'>
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">Shopping List</h2>
          <button type='button' onClick={ () => setShowModal(true) } className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded drop-shadow-md"> Add Item </button>
        </div>       
        {/* <ul className="mt-4">
          {items.map((item) => (
          <li className="flex justify-between items-center bg-gray-100 p-4 mb-3 rounded-md drop-shadow-md">
            <span key={item.id}>{item.name}</span>
          </li>
        ))}
        </ul> */}
        <ul className="mt-4">
          {items.map((item) => {
            const { id, name } = item;
            return (
              <li key={id}className="flex justify-between items-center bg-gray-100 p-4 mb-3 rounded-md drop-shadow-md">
                <span className='font-weight-500'>{name}</span>
                <button className="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">X</button>
              </li>
            )
          })}
          
        </ul>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const items = await prisma.shoppingItem.findMany();
  return {
    props: {
      items,
    },
  };

}

export default Home
